spring.application.name=electionmanagmentsystem
spring.datasource.url=jdbc:postgresql://localhost:5432/election_management
spring.datasource.username=anish.tewari
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true